services:
  vk_bot:
    build:
      context: vk_bot
      dockerfile: Dockerfile
    env_file:
      - vk_bot/.env
      - mongo/.env
      - storage/.env
    volumes:
      - ./assets:/app/assets
    networks:
      - app_network

  mongo:
    image: mongo:latest
    restart: always
    env_file: mongo/.env
    volumes:
      - quest_mongo:/data/db
    networks:
      - app_network

  redis:
    build:
      context: storage
      dockerfile: Dockerfile
    restart: always
    env_file: storage/.env
    volumes:
      - quest_redis:/data
    networks:
      - app_network

volumes:
  quest_mongo:
    name: 
      quest_mongo
    driver: local
  quest_redis:
    name: 
      quest_redis
    driver: local

networks:
  app_network:
    driver: bridge